name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: List files after build
        run: ls -la dist/
        
      - name: Deploy to Yandex Object Storage
        uses: MrMeison/yc-object-storage-action@main
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.BUCKET }}
          sourceDir: ./dist
          clear: true
